import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface MealReportStudent {
  name: string;
  token_number: string;
  rna_number: string;
  room_no: string;
}

interface MealReportData {
  date: string;
  dateFormatted: string;
  meal: string;
  mealLabel: string;
  students: MealReportStudent[];
  totalCount: number;
}

const mealColors: Record<string, [number, number, number]> = {
  breakfast: [245, 158, 11],
  lunch: [14, 165, 233],
  dinner: [99, 102, 241],
};

export function generateMealReport(data: MealReportData) {
  const color = mealColors[data.meal] ?? [45, 80, 22];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  // ── HEADER BAR ─────────────────────────────────
  doc.setFillColor(...color);
  doc.rect(0, 0, 210, 28, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(
    "BANGLADESH ARMY UNIVERSITY OF SCIENCE AND TECHNOLOGY",
    105,
    9,
    { align: "center" }
  );
  doc.text("Online Hall Meal Management System", 105, 14, { align: "center" });

  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(`${data.mealLabel} Report`, 105, 22, { align: "center" });

  // ── META INFO ──────────────────────────────────
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Date: ${data.dateFormatted}`, 14, 36);
  doc.text(`Meal: ${data.mealLabel}`, 14, 42);
  doc.text(
    `Generated: ${new Date().toLocaleString("en-BD", {
      timeZone: "Asia/Dhaka",
    })}`,
    14,
    48
  );
  doc.text(
    `Total Students: ${data.totalCount}`,
    196,
    36,
    { align: "right" }
  );

  // ── DIVIDER ────────────────────────────────────
  doc.setDrawColor(...color);
  doc.setLineWidth(0.5);
  doc.line(14, 52, 196, 52);

  // ── TABLE ──────────────────────────────────────
  autoTable(doc, {
    startY: 56,
    head: [["#", "Student Name", "Token Number", "Room No."]],
    body: data.students.map((s, i) => [
      i + 1,
      s.name,
      s.token_number ?? "N/A",
      s.room_no ?? "N/A",
    ]),
    headStyles: {
      fillColor: color,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9.5,
      textColor: [30, 30, 30],
    },
    alternateRowStyles: {
      fillColor: [248, 248, 248],
    },
    columnStyles: {
      0: { cellWidth: 12, halign: "center" },
      1: { cellWidth: 90 },
      2: { cellWidth: 50, halign: "center", font: "courier" },
      3: { cellWidth: 30, halign: "center" },
    },
    margin: { left: 14, right: 14 },
    tableLineColor: [220, 220, 220],
    tableLineWidth: 0.2,
  });

  // ── TOTAL COUNT BOX ────────────────────────────
  const finalY = (doc as any).lastAutoTable?.finalY ?? 200;
  const boxY = finalY + 6;
  doc.setFillColor(
    Math.min(255, color[0] + 180),
    Math.min(255, color[1] + 180),
    Math.min(255, color[2] + 180)
  );
  doc.rect(14, boxY, 182, 10, "F");
  doc.setTextColor(...color);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(
    `Total ${data.mealLabel} Count: ${data.totalCount} students`,
    105,
    boxY + 6.5,
    { align: "center" }
  );

  // ── FOOTER ─────────────────────────────────────
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text(
    "This report is auto-generated by OHHM. For official use only.",
    105,
    285,
    { align: "center" }
  );

  // ── SAVE ───────────────────────────────────────
  const filename = `${data.meal}-report-${data.date}.pdf`;
  doc.save(filename);
}
